import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

/*
  Generates a frontend-friendly addresses file at whale.fun/lib/addresses.ts
  by reading all JSON files under contracts/deployments/.

  Usage:
    tsx contracts/scripts/utils/generate-addresses.ts

  It builds a map keyed by chainId with contract names & addresses.
*/

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const repoRoot = path.resolve(__dirname, "../../..");
const deploymentsDir = path.join(repoRoot, "contracts", "deployments");
const outputFile = path.join(repoRoot, "lib", "addresses.ts");

function main() {
  if (!fs.existsSync(deploymentsDir)) {
    throw new Error(`Deployments dir not found: ${deploymentsDir}`);
  }

  const files = fs
    .readdirSync(deploymentsDir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => path.join(deploymentsDir, f));

  const deployments: Array<{
    network: string;
    chainId: number;
    contracts: Record<string, string>;
    file: string;
    timestamp?: string;
    deployer?: string;
  }> = [];

  for (const file of files) {
    try {
      const data = JSON.parse(fs.readFileSync(file, "utf8"));
      if (data && typeof data === "object" && data.chainId && data.contracts) {
        deployments.push({ ...data, file });
      }
    } catch (e) {
      console.warn(`[generate-addresses] Skipping invalid file: ${file}`);
    }
  }

  if (deployments.length === 0) {
    throw new Error("No valid deployment JSON files found under contracts/deployments/");
  }

  // Keep the latest per chainId (by file mtime)
  const latestByChain: Record<number, (typeof deployments)[number]> = {};
  for (const d of deployments) {
    const prev = latestByChain[d.chainId];
    if (!prev) {
      latestByChain[d.chainId] = d;
      continue;
    }
    const prevM = fs.statSync(prev.file).mtimeMs;
    const currM = fs.statSync(d.file).mtimeMs;
    if (currM > prevM) latestByChain[d.chainId] = d;
  }

  const header = `// AUTO-GENERATED by contracts/scripts/utils/generate-addresses.ts\n`;
  const body: string[] = [];
  body.push(`export type ContractAddresses = { [name: string]: ` + "`0x${string}`" + ` };`);
  body.push(`export type NetworkDeployment = { name: string; chainId: number; contracts: ContractAddresses };`);
  body.push(`export const DEPLOYMENTS: Record<number, NetworkDeployment> = {`);

  for (const [chainIdStr, dep] of Object.entries(latestByChain)) {
    const chainId = Number(chainIdStr);
    const contractsEntries = Object.entries(dep.contracts)
      .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v as string)},`)
      .join("\n");
    body.push(`  ${chainId}: {`);
    body.push(`    name: ${JSON.stringify(dep.network)},`);
    body.push(`    chainId: ${chainId},`);
    body.push(`    contracts: {\n${contractsEntries}\n    },`);
    body.push(`  },`);
  }
  body.push(`};`);

  body.push(`\nexport function getAddresses(chainId?: number): ContractAddresses {`);
  body.push(`  const id = chainId ?? Number(process.env.NEXT_PUBLIC_CHAIN_ID ?? 16602);`);
  body.push(`  return DEPLOYMENTS[id]?.contracts ?? {};`);
  body.push(`}`);

  const output = header + "\n" + body.join("\n");

  // Ensure lib dir exists
  const libDir = path.dirname(outputFile);
  if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });

  fs.writeFileSync(outputFile, output);
  console.log(`[generate-addresses] Wrote ${outputFile}`);
}

main();
